### ISSUE TITLE
Country code is not saved to field

### ISSUE THREAD

**Issue by miamicityman** [mtcextendee/mautic-international-phone-input-bundle#2]
Hello there.

Just installed the plugin and works fine in the front end of the form.

In the back end however, the country code is NOT saved with the phone number, at least not "mobile phone number" field.

Have I configured the plug-in wrong? Is there a solution?

![Screenshot_3](https://user-images.githubusercontent.com/57761794/78935267-69ed9c80-7a7a-11ea-8197-3dc943316164.png)

![Screenshot_5](https://user-images.githubusercontent.com/57761794/78935279-6eb25080-7a7a-11ea-8e11-91048f1207ff.png)

Thanks,

**Comment by miamicityman** [comment]
I've been trying to get this plug-in to work correctly and save the **Country Code** to the contact mobile phone field without success. I've tried changes to the following files but nothing works.

• intlTelInput-jquery.js
• intlTelInput.js

![image](https://user-images.githubusercontent.com/57761794/79155884-da106100-7d9f-11ea-902c-c3c106200316.png)

I've also tried looking to find where the placeholder number is being called from ... equally without success.

Any help would be much appreciated.

![Screenshot_6](https://user-images.githubusercontent.com/57761794/79155747-9e759700-7d9f-11ea-9dc7-50b6bd9d8710.png)

**Comment by miamicityman** [comment]
No success. 

I haven't found how to extract full international numbers using `getNumber` command.

**Comment by miamicityman** [comment]
Well, if anyone is interested ... the solution we found was to hack the core.

Line 254 at

/app/bundles/FormBundle/Model/SubmissionModel.php

Not the greatest solution, but it works.

![image](https://user-images.githubusercontent.com/57761794/79368808-ff2ade00-7f1d-11ea-8c62-d4c92891bbca.png)

**Comment by jpgiron1981** [comment]
Hello, i made your hacke, but now give me a message, that the field its required always... don't work my friend!

But on my mautic version, it have this sentence:  $value = (isset($post[$alias])) ? $post[$alias] : '';  

/** @var Field $f */
        foreach ($fields as $f) {
            $id    = $f->getId();
            $type  = $f->getType();
            $alias = $f->getAlias();
            $value = (isset($post[$alias])) ? $post[$alias] : '';

**Comment by jpgiron1981** [comment]
What i do its this

on EventListener/FormValidationSubscriber.php

on line 61 

$fullPhoneNumber = ArrayHelper::getValue($field->getAlias().'_full', $this->request->request->get('mauticform'));

replace it 

$fullPhoneNumber = ArrayHelper::getValue($field->getAlias().'', $this->request->request->get('mauticform'));

and on Controller/JsController.php

on line 66

hiddenInput: elem.getAttribute('data-field-alias')+'_full',

replace it 

hiddenInput: elem.getAttribute('data-field-alias')+'',

and this make the form capture the number with the international prefix and store on the contact field you select (i put on mobile field). BUT you need to put the field as no required on Validation because if you tue as required, the form doesnt continue. Maybe someone else can make a better solution?

Regards

**Comment by kuzmany** [comment]
Today released version for M3, should fixed also this issue:
 https://github.com/mtcextendee/mautic-international-phone-input-bundle/releases/tag/1.2.0
